# Generated by Django 4.2.9 on 2025-10-31 18:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="age",
            field=models.IntegerField(blank=True, null=True, verbose_name="Age"),
        ),
    ]
