# Generated by Django 5.2.7 on 2025-11-04 19:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivationalMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('author', models.CharField(blank=True, max_length=200, null=True, verbose_name='Autor')),
                ('category', models.CharField(choices=[('motivation', 'Motivación'), ('job_search', 'Búsqueda de Empleo'), ('career', 'Desarrollo de Carrera'), ('perseverance', 'Perseverancia'), ('success', 'Éxito'), ('growth', 'Crecimiento'), ('positivity', 'Positividad')], default='motivation', max_length=50, verbose_name='Categoría')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('priority', models.IntegerField(default=0, help_text='Mayor prioridad = más probabilidad de mostrarse', verbose_name='Prioridad')),
                ('times_shown', models.IntegerField(default=0, verbose_name='Veces mostrado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mensaje Motivacional',
                'verbose_name_plural': 'Mensajes Motivacionales',
                'db_table': 'motivational_messages',
                'ordering': ['-priority', '-created_at'],
            },
        ),
    ]
