# Generated by Django 4.2.9 on 2025-11-06 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_motivationalmessage"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobAlertPreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(default=True, verbose_name="Alertas Activadas"),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("instant", "Inmediata"),
                            ("daily", "Diaria"),
                            ("weekly", "Semanal"),
                            ("disabled", "Desactivada"),
                        ],
                        default="instant",
                        max_length=20,
                        verbose_name="Frecuencia",
                    ),
                ),
                (
                    "match_by_skills",
                    models.BooleanField(
                        default=True, verbose_name="Coincidir por Habilidades"
                    ),
                ),
                (
                    "match_by_location",
                    models.BooleanField(
                        default=True, verbose_name="Coincidir por Ubicación"
                    ),
                ),
                (
                    "match_by_experience",
                    models.BooleanField(
                        default=True, verbose_name="Coincidir por Experiencia"
                    ),
                ),
                (
                    "preferred_job_types",
                    models.JSONField(
                        blank=True,
                        default=list,
                        verbose_name="Tipos de Trabajo Preferidos",
                    ),
                ),
                (
                    "preferred_locations",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Ubicaciones Preferidas"
                    ),
                ),
                (
                    "remote_only",
                    models.BooleanField(default=False, verbose_name="Solo Remoto"),
                ),
                (
                    "min_salary",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Salario Mínimo",
                    ),
                ),
                (
                    "last_alert_sent",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Última Alerta Enviada"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_alert_preference",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Preferencia de Alerta de Trabajo",
                "verbose_name_plural": "Preferencias de Alertas de Trabajo",
                "db_table": "job_alert_preferences",
            },
        ),
    ]
