# Generated by Django 4.2.9 on 2025-11-06 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_jobalertpreference"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nombre")),
                (
                    "logo_url",
                    models.URLField(blank=True, null=True, verbose_name="URL del logo"),
                ),
                (
                    "website",
                    models.URLField(blank=True, null=True, verbose_name="Sitio web"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activa")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Empresa",
                "verbose_name_plural": "Empresas",
                "db_table": "companies",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Título")),
                ("description", models.TextField(verbose_name="Descripción")),
                (
                    "required_skills",
                    models.JSONField(
                        default=list,
                        help_text="Lista de skills necesarias para el curso",
                        verbose_name="Habilidades requeridas",
                    ),
                ),
                (
                    "skills_taught",
                    models.JSONField(
                        default=list,
                        help_text="Lista de skills que se aprenden en el curso",
                        verbose_name="Habilidades enseñadas",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("beginner", "Principiante"),
                            ("intermediate", "Intermedio"),
                            ("advanced", "Avanzado"),
                            ("expert", "Experto"),
                        ],
                        default="beginner",
                        max_length=20,
                        verbose_name="Nivel",
                    ),
                ),
                (
                    "duration_value",
                    models.IntegerField(verbose_name="Duración (valor)"),
                ),
                (
                    "duration_unit",
                    models.CharField(
                        choices=[
                            ("hours", "Horas"),
                            ("days", "Días"),
                            ("weeks", "Semanas"),
                            ("months", "Meses"),
                        ],
                        max_length=20,
                        verbose_name="Duración (unidad)",
                    ),
                ),
                ("course_url", models.URLField(verbose_name="URL del curso")),
                (
                    "thumbnail_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="URL de miniatura"
                    ),
                ),
                ("is_free", models.BooleanField(default=False, verbose_name="Gratis")),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Precio",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="USD", max_length=3, verbose_name="Moneda"
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=3,
                        verbose_name="Calificación",
                    ),
                ),
                (
                    "enrollments",
                    models.IntegerField(default=0, verbose_name="Inscripciones"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                ("priority", models.IntegerField(default=0, verbose_name="Prioridad")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courses",
                        to="users.company",
                        verbose_name="Empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Curso",
                "verbose_name_plural": "Cursos",
                "db_table": "courses",
                "ordering": ["-priority", "-rating", "-enrollments"],
            },
        ),
        migrations.CreateModel(
            name="UserCourse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("enrolled", "Inscrito"),
                            ("in_progress", "En progreso"),
                            ("completed", "Completado"),
                            ("abandoned", "Abandonado"),
                        ],
                        default="enrolled",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "progress_percentage",
                    models.IntegerField(default=0, verbose_name="Progreso (%)"),
                ),
                ("enrolled_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("last_accessed", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments_detail",
                        to="users.course",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrolled_courses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Curso de Usuario",
                "verbose_name_plural": "Cursos de Usuarios",
                "db_table": "user_courses",
                "ordering": ["-enrolled_at"],
                "unique_together": {("user", "course")},
            },
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["company", "is_active"], name="courses_company_39da34_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["-priority", "-rating"], name="courses_priorit_166688_idx"
            ),
        ),
    ]
