# Generated by Django 4.2.9 on 2025-11-06 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_company_course_usercourse_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SuccessStory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company", models.CharField(max_length=200)),
                ("position", models.CharField(max_length=200)),
                ("hire_date", models.DateField()),
                (
                    "salary_range",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("0-30k", "$0 - $30,000"),
                            ("30k-50k", "$30,000 - $50,000"),
                            ("50k-70k", "$50,000 - $70,000"),
                            ("70k-100k", "$70,000 - $100,000"),
                            ("100k+", "$100,000+"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("is_willing_to_mentor", models.BooleanField(default=False)),
                ("max_mentees", models.IntegerField(default=3)),
                (
                    "success_description",
                    models.TextField(
                        help_text="¿Cómo conseguiste el empleo? Consejos para otros"
                    ),
                ),
                (
                    "key_skills_used",
                    models.JSONField(
                        default=list,
                        help_text="Skills que fueron clave para conseguir el empleo",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="success_story",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Historia de Éxito",
                "verbose_name_plural": "Historias de Éxito",
                "db_table": "success_stories",
                "ordering": ["-hire_date"],
            },
        ),
        migrations.CreateModel(
            name="ProfileMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "similarity_score",
                    models.IntegerField(help_text="Similarity score 0-100"),
                ),
                (
                    "matching_skills",
                    models.JSONField(default=list, help_text="Skills in common"),
                ),
                ("skill_overlap_percentage", models.FloatField(default=0.0)),
                ("same_location", models.BooleanField(default=False)),
                ("similar_experience_level", models.BooleanField(default=False)),
                ("calculated_at", models.DateTimeField(auto_now=True)),
                (
                    "matched_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matched_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_matches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "profile_matches",
                "ordering": ["-similarity_score"],
                "indexes": [
                    models.Index(
                        fields=["user", "-similarity_score"],
                        name="profile_mat_user_id_31927f_idx",
                    ),
                    models.Index(
                        fields=["matched_user", "-similarity_score"],
                        name="profile_mat_matched_04e1d2_idx",
                    ),
                ],
                "unique_together": {("user", "matched_user")},
            },
        ),
        migrations.CreateModel(
            name="MentorshipRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("accepted", "Aceptada"),
                            ("declined", "Rechazada"),
                            ("cancelled", "Cancelada"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("message", models.TextField(help_text="Mensaje de presentación")),
                ("response_message", models.TextField(blank=True, null=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "from_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mentorship_requests_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "to_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mentorship_requests_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "mentorship_requests",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["from_user", "-created_at"],
                        name="mentorship__from_us_d06edf_idx",
                    ),
                    models.Index(
                        fields=["to_user", "status", "-created_at"],
                        name="mentorship__to_user_66ff70_idx",
                    ),
                ],
                "unique_together": {("from_user", "to_user")},
            },
        ),
    ]
