# Generated by Django 4.2.9 on 2025-11-06 20:54

import apps.users.models_referral
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_successstory_profilematch_mentorshiprequest"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "reward_type",
                    models.CharField(
                        choices=[
                            ("badge", "Insignia"),
                            ("course_discount", "Descuento en Curso"),
                            ("premium_feature", "Feature Premium"),
                            ("course_free", "Curso Gratis"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "points_required",
                    models.IntegerField(verbose_name="Puntos Requeridos"),
                ),
                ("icon", models.CharField(default="🎁", max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "max_redemptions_per_user",
                    models.IntegerField(
                        default=1, verbose_name="Máximo de Canjes por Usuario"
                    ),
                ),
                (
                    "total_available",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Total Disponible"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Recompensa",
                "verbose_name_plural": "Recompensas",
                "db_table": "rewards",
                "ordering": ["points_required"],
            },
        ),
        migrations.AddField(
            model_name="user",
            name="points",
            field=models.IntegerField(default=0, verbose_name="Puntos Acumulados"),
        ),
        migrations.CreateModel(
            name="RewardRedemption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("points_spent", models.IntegerField()),
                ("redeemed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reward",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="redemptions",
                        to="users.reward",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reward_redemptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Canje de Recompensa",
                "verbose_name_plural": "Canjes de Recompensas",
                "db_table": "reward_redemptions",
                "ordering": ["-redeemed_at"],
            },
        ),
        migrations.CreateModel(
            name="ReferralCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        default=apps.users.models_referral.generate_referral_code,
                        max_length=10,
                        unique=True,
                        verbose_name="Código de Referido",
                    ),
                ),
                (
                    "total_referrals",
                    models.IntegerField(default=0, verbose_name="Total de Referidos"),
                ),
                (
                    "total_points_earned",
                    models.IntegerField(
                        default=0, verbose_name="Puntos Ganados por Referidos"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referral_code",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Código de Referido",
                "verbose_name_plural": "Códigos de Referidos",
                "db_table": "referral_codes",
            },
        ),
        migrations.CreateModel(
            name="Referral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("registered", "Registrado"),
                            ("profile_completed", "Perfil Completado"),
                            ("employed", "Empleado"),
                        ],
                        default="registered",
                        max_length=20,
                    ),
                ),
                ("registration_points_awarded", models.BooleanField(default=False)),
                (
                    "profile_completion_points_awarded",
                    models.BooleanField(default=False),
                ),
                ("employment_points_awarded", models.BooleanField(default=False)),
                ("referred_at", models.DateTimeField(auto_now_add=True)),
                ("last_milestone_at", models.DateTimeField(auto_now=True)),
                (
                    "referral_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referrals",
                        to="users.referralcode",
                    ),
                ),
                (
                    "referred",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referred_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Referido",
                    ),
                ),
                (
                    "referrer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referrals_made",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Referidor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Referido",
                "verbose_name_plural": "Referidos",
                "db_table": "referrals",
            },
        ),
        migrations.CreateModel(
            name="PointsTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("referral_register", "Referido Registrado"),
                            ("referral_profile", "Referido Completó Perfil"),
                            ("referral_employed", "Referido Consiguió Empleo"),
                            ("welcome_bonus", "Bono de Bienvenida"),
                            ("challenge_complete", "Reto Completado"),
                            ("streak_bonus", "Bonus de Racha"),
                            ("course_complete", "Curso Completado"),
                            ("redeem", "Canje de Puntos"),
                            ("admin_adjustment", "Ajuste Administrativo"),
                        ],
                        max_length=30,
                    ),
                ),
                ("points", models.IntegerField(verbose_name="Puntos")),
                (
                    "description",
                    models.CharField(max_length=255, verbose_name="Descripción"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "related_referral",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="points_transactions",
                        to="users.referral",
                    ),
                ),
                (
                    "related_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="points_transactions_about",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario Relacionado",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="points_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Transacción de Puntos",
                "verbose_name_plural": "Transacciones de Puntos",
                "db_table": "points_transactions",
                "ordering": ["-created_at"],
            },
        ),
    ]
