# Generated by Django 5.2.7 on 2025-11-04 19:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('icon', models.CharField(default='🎯', max_length=50, verbose_name='Icono')),
                ('challenge_type', models.CharField(choices=[('daily', 'Reto Diario'), ('weekly', 'Reto Semanal'), ('special', 'Reto Especial')], max_length=20, verbose_name='Tipo')),
                ('category', models.CharField(choices=[('applications', 'Aplicaciones'), ('profile', 'Perfil'), ('learning', 'Aprendizaje'), ('networking', 'Networking'), ('streak', 'Racha'), ('exploration', 'Exploración')], max_length=50, verbose_name='Categoría')),
                ('target_action', models.CharField(help_text='Ej: apply_to_jobs, update_profile, view_jobs', max_length=50, verbose_name='Acción objetivo')),
                ('target_count', models.IntegerField(default=1, verbose_name='Cantidad requerida')),
                ('points_reward', models.IntegerField(default=10, verbose_name='Puntos de recompensa')),
                ('bonus_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=3, verbose_name='Multiplicador de bonus')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Fecha inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha fin')),
                ('priority', models.IntegerField(default=0, verbose_name='Prioridad')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Reto',
                'verbose_name_plural': 'Retos',
                'db_table': 'challenges',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='pointshistory',
            name='action',
            field=models.CharField(choices=[('login', 'Daily Login'), ('application', 'Job Application'), ('profile_update', 'Profile Update'), ('streak_milestone', 'Streak Milestone'), ('achievement', 'Achievement Earned'), ('job_saved', 'Job Saved'), ('job_viewed', 'Job Viewed'), ('referral', 'Referral'), ('bonus', 'Bonus'), ('challenge_completed', 'Challenge Completed')], max_length=20),
        ),
        migrations.CreateModel(
            name='UserChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_progress', models.IntegerField(default=0, verbose_name='Progreso actual')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('completed', 'Completado'), ('expired', 'Expirado'), ('abandoned', 'Abandonado')], default='active', max_length=20, verbose_name='Estado')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('points_earned', models.IntegerField(default=0, verbose_name='Puntos ganados')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='streaks.challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_challenges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reto de Usuario',
                'verbose_name_plural': 'Retos de Usuarios',
                'db_table': 'user_challenges',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['user', 'status', '-started_at'], name='user_challe_user_id_3c62e1_idx')],
                'unique_together': {('user', 'challenge', 'started_at')},
            },
        ),
    ]
